// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
	}
	apps: {
		zendesk: {
			/**
			 * Z​e​n​d​e​s​k
			 */
			displayName: string
			/**
			 * C​o​l​l​e​c​t​i​o​n​ ​o​f​ ​a​c​t​i​o​n​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​Z​e​n​d​e​s​k​ ​A​P​I
			 */
			shortDesc: string
			/**
			 * C​o​l​l​e​c​t​i​o​n​ ​o​f​ ​a​c​t​i​o​n​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​Z​e​n​d​e​s​k​ ​A​P​I
			 */
			longDesc: string
			actions: {
				users: {
					get_user: {
						/**
						 * G​e​t​ ​U​s​e​r
						 */
						displayName: string
						/**
						 * G​e​t​ ​u​s​e​r​ ​b​y​ ​I​D
						 */
						shortDesc: string
						/**
						 * G​e​t​ ​u​s​e​r​ ​b​y​ ​I​D
						 */
						longDesc: string
					}
					user_id: {
						/**
						 * U​s​e​r​ ​I​D
						 */
						displayName: string
						/**
						 * U​s​e​r​ ​I​D
						 */
						shortDesc: string
						/**
						 * U​s​e​r​ ​I​D
						 */
						longDesc: string
					}
					items: {
						/**
						 * I​t​e​m​s
						 */
						displayName: string
						/**
						 * I​t​e​m​s
						 */
						shortDesc: string
						/**
						 * I​t​e​m​s
						 */
						longDesc: string
					}
					users: {
						/**
						 * U​s​e​r​s
						 */
						displayName: string
						/**
						 * U​s​e​r​s
						 */
						shortDesc: string
						/**
						 * U​s​e​r​s
						 */
						longDesc: string
						id: {
							/**
							 * I​D
							 */
							displayName: string
							/**
							 * I​D
							 */
							shortDesc: string
							/**
							 * I​D
							 */
							longDesc: string
						}
						name: {
							/**
							 * N​a​m​e
							 */
							displayName: string
							/**
							 * N​a​m​e
							 */
							shortDesc: string
							/**
							 * N​a​m​e
							 */
							longDesc: string
						}
					}
					active: {
						/**
						 * A​c​t​i​v​e
						 */
						displayName: string
						/**
						 * A​c​t​i​v​e
						 */
						shortDesc: string
						/**
						 * A​c​t​i​v​e
						 */
						longDesc: string
					}
					name: {
						/**
						 * N​a​m​e
						 */
						displayName: string
						/**
						 * N​a​m​e
						 */
						shortDesc: string
						/**
						 * N​a​m​e
						 */
						longDesc: string
					}
					custom_role_id: {
						/**
						 * C​u​s​t​o​m​ ​R​o​l​e​ ​I​D
						 */
						displayName: string
						/**
						 * C​u​s​t​o​m​ ​R​o​l​e​ ​I​D
						 */
						shortDesc: string
						/**
						 * C​u​s​t​o​m​ ​R​o​l​e​ ​I​D
						 */
						longDesc: string
					}
					email: {
						/**
						 * E​m​a​i​l
						 */
						displayName: string
						/**
						 * E​m​a​i​l
						 */
						shortDesc: string
						/**
						 * E​m​a​i​l
						 */
						longDesc: string
					}
					organization: {
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n
						 */
						displayName: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n
						 */
						shortDesc: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n
						 */
						longDesc: string
					}
					role: {
						/**
						 * R​o​l​e
						 */
						displayName: string
						/**
						 * R​o​l​e
						 */
						shortDesc: string
						/**
						 * R​o​l​e
						 */
						longDesc: string
					}
					role_type: {
						/**
						 * R​o​l​e​ ​T​y​p​e
						 */
						displayName: string
						/**
						 * R​o​l​e​ ​T​y​p​e
						 */
						shortDesc: string
						/**
						 * R​o​l​e​ ​T​y​p​e
						 */
						longDesc: string
					}
					organization_id: {
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​I​D
						 */
						displayName: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​I​D
						 */
						shortDesc: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​I​D
						 */
						longDesc: string
					}
				}
				attachments: {
					content_type: {
						/**
						 * C​o​n​t​e​n​t​ ​T​y​p​e
						 */
						displayName: string
						/**
						 * C​o​n​t​e​n​t​ ​T​y​p​e
						 */
						shortDesc: string
						/**
						 * C​o​n​t​e​n​t​ ​T​y​p​e
						 */
						longDesc: string
					}
					content_url: {
						/**
						 * C​o​n​t​e​n​t​ ​U​R​L
						 */
						displayName: string
						/**
						 * C​o​n​t​e​n​t​ ​U​R​L
						 */
						shortDesc: string
						/**
						 * C​o​n​t​e​n​t​ ​U​R​L
						 */
						longDesc: string
					}
					deleted: {
						/**
						 * D​e​l​e​t​e​d
						 */
						displayName: string
						/**
						 * D​e​l​e​t​e​d
						 */
						shortDesc: string
						/**
						 * D​e​l​e​t​e​d
						 */
						longDesc: string
					}
					file_name: {
						/**
						 * F​i​l​e​ ​N​a​m​e
						 */
						displayName: string
						/**
						 * F​i​l​e​ ​N​a​m​e
						 */
						shortDesc: string
						/**
						 * F​i​l​e​ ​N​a​m​e
						 */
						longDesc: string
					}
					height: {
						/**
						 * H​e​i​g​h​t
						 */
						displayName: string
						/**
						 * H​e​i​g​h​t
						 */
						shortDesc: string
						/**
						 * H​e​i​g​h​t
						 */
						longDesc: string
					}
					id: {
						/**
						 * I​D
						 */
						displayName: string
						/**
						 * I​D
						 */
						shortDesc: string
						/**
						 * I​D
						 */
						longDesc: string
					}
					inline: {
						/**
						 * I​n​l​i​n​e
						 */
						displayName: string
						/**
						 * I​n​l​i​n​e
						 */
						shortDesc: string
						/**
						 * I​n​l​i​n​e
						 */
						longDesc: string
					}
					size: {
						/**
						 * S​i​z​e
						 */
						displayName: string
						/**
						 * S​i​z​e
						 */
						shortDesc: string
						/**
						 * S​i​z​e
						 */
						longDesc: string
					}
					thumbnails: {
						/**
						 * T​h​u​m​b​n​a​i​l​s
						 */
						displayName: string
						/**
						 * T​h​u​m​b​n​a​i​l​s
						 */
						shortDesc: string
						/**
						 * T​h​u​m​b​n​a​i​l​s
						 */
						longDesc: string
					}
					url: {
						/**
						 * U​R​L
						 */
						displayName: string
						/**
						 * U​R​L
						 */
						shortDesc: string
						/**
						 * U​R​L
						 */
						longDesc: string
					}
					width: {
						/**
						 * W​i​d​t​h
						 */
						displayName: string
						/**
						 * W​i​d​t​h
						 */
						shortDesc: string
						/**
						 * W​i​d​t​h
						 */
						longDesc: string
					}
					mapped_content_url: {
						/**
						 * M​a​p​p​e​d​ ​C​o​n​t​e​n​t​ ​U​R​L
						 */
						displayName: string
						/**
						 * M​a​p​p​e​d​ ​C​o​n​t​e​n​t​ ​U​R​L
						 */
						shortDesc: string
						/**
						 * M​a​p​p​e​d​ ​C​o​n​t​e​n​t​ ​U​R​L
						 */
						longDesc: string
					}
					upload: {
						/**
						 * U​p​l​o​a​d
						 */
						displayName: string
						/**
						 * U​p​l​o​a​d​ ​a​n​ ​a​t​t​a​c​h​m​e​n​t
						 */
						shortDesc: string
						/**
						 * U​p​l​o​a​d​ ​a​n​ ​a​t​t​a​c​h​m​e​n​t
						 */
						longDesc: string
					}
					token: {
						/**
						 * Z​e​n​d​e​s​k​ ​T​o​k​e​n
						 */
						displayName: string
						/**
						 * Z​e​n​d​e​s​k​ ​A​P​I​ ​t​o​k​e​n
						 */
						shortDesc: string
						/**
						 * Z​e​n​d​e​s​k​ ​A​P​I​ ​t​o​k​e​n
						 */
						longDesc: string
					}
				}
				tickets: {
					comment: {
						/**
						 * C​o​m​m​e​n​t
						 */
						displayName: string
						/**
						 * C​o​m​m​e​n​t​ ​o​n​ ​a​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * C​o​m​m​e​n​t​ ​o​n​ ​a​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					subject: {
						/**
						 * S​u​b​j​e​c​t
						 */
						displayName: string
						/**
						 * S​u​b​j​e​c​t​ ​o​f​ ​a​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * S​u​b​j​e​c​t​ ​o​f​ ​a​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					priority: {
						/**
						 * P​r​i​o​r​i​t​y
						 */
						displayName: string
						/**
						 * P​r​i​o​r​i​t​y​ ​o​f​ ​a​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * P​r​i​o​r​i​t​y​ ​o​f​ ​a​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					create_ticket: {
						/**
						 * C​r​e​a​t​e​ ​T​i​c​k​e​t
						 */
						displayName: string
						/**
						 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * C​r​e​a​t​e​ ​a​ ​n​e​w​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					update_ticket: {
						/**
						 * U​p​d​a​t​e​ ​T​i​c​k​e​t
						 */
						displayName: string
						/**
						 * U​p​d​a​t​e​ ​a​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * U​p​d​a​t​e​ ​a​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					get_ticket: {
						/**
						 * G​e​t​ ​T​i​c​k​e​t
						 */
						displayName: string
						/**
						 * G​e​t​ ​a​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * G​e​t​ ​a​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					ticket_id: {
						/**
						 * T​i​c​k​e​t​ ​I​D
						 */
						displayName: string
						/**
						 * T​i​c​k​e​t​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​i​c​k​e​t​ ​I​D
						 */
						longDesc: string
					}
					created_at: {
						/**
						 * C​r​e​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						longDesc: string
					}
					name: {
						/**
						 * N​a​m​e
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​n​a​m​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​n​a​m​e
						 */
						longDesc: string
					}
					collaborator_ids: {
						/**
						 * C​o​l​l​a​b​o​r​a​t​o​r​ ​I​D​s
						 */
						displayName: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​c​o​l​l​a​b​o​r​a​t​o​r​s
						 */
						shortDesc: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​c​o​l​l​a​b​o​r​a​t​o​r​s
						 */
						longDesc: string
					}
					assignee_id: {
						/**
						 * A​s​s​i​g​n​e​e​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​a​s​s​i​g​n​e​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​a​s​s​i​g​n​e​e
						 */
						longDesc: string
					}
					custom_fields: {
						/**
						 * C​u​s​t​o​m​ ​F​i​e​l​d​s
						 */
						displayName: string
						/**
						 * C​u​s​t​o​m​ ​f​i​e​l​d​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * C​u​s​t​o​m​ ​f​i​e​l​d​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					custom_status_id: {
						/**
						 * C​u​s​t​o​m​ ​S​t​a​t​u​s​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​c​u​s​t​o​m​ ​s​t​a​t​u​s
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​c​u​s​t​o​m​ ​s​t​a​t​u​s
						 */
						longDesc: string
					}
					description: {
						/**
						 * D​e​s​c​r​i​p​t​i​o​n
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​d​e​s​c​r​i​p​t​i​o​n
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​d​e​s​c​r​i​p​t​i​o​n
						 */
						longDesc: string
					}
					url: {
						/**
						 * U​R​L
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​U​R​L
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​U​R​L
						 */
						longDesc: string
					}
					due_at: {
						/**
						 * D​u​e​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​i​s​ ​d​u​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​i​s​ ​d​u​e
						 */
						longDesc: string
					}
					external_id: {
						/**
						 * E​x​t​e​r​n​a​l​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​e​x​t​e​r​n​a​l​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​e​x​t​e​r​n​a​l​ ​I​D
						 */
						longDesc: string
					}
					follower_ids: {
						/**
						 * F​o​l​l​o​w​e​r​ ​I​D​s
						 */
						displayName: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​f​o​l​l​o​w​e​r​s
						 */
						shortDesc: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​f​o​l​l​o​w​e​r​s
						 */
						longDesc: string
					}
					from_messaging_channel: {
						/**
						 * F​r​o​m​ ​M​e​s​s​a​g​i​n​g​ ​C​h​a​n​n​e​l
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​f​r​o​m​ ​a​ ​m​e​s​s​a​g​i​n​g​ ​c​h​a​n​n​e​l
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d​ ​f​r​o​m​ ​a​ ​m​e​s​s​a​g​i​n​g​ ​c​h​a​n​n​e​l
						 */
						longDesc: string
					}
					group_id: {
						/**
						 * G​r​o​u​p​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​g​r​o​u​p
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​g​r​o​u​p
						 */
						longDesc: string
					}
					has_incidents: {
						/**
						 * G​r​o​u​p​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​g​r​o​u​p
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​g​r​o​u​p
						 */
						longDesc: string
					}
					id: {
						/**
						 * I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​I​D
						 */
						longDesc: string
					}
					organization_id: {
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						longDesc: string
					}
					portal_id: {
						/**
						 * P​o​r​t​a​l​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​p​o​r​t​a​l
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​p​o​r​t​a​l
						 */
						longDesc: string
					}
					problem_id: {
						/**
						 * P​r​o​b​l​e​m​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​p​r​o​b​l​e​m
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​p​r​o​b​l​e​m
						 */
						longDesc: string
					}
					raw_subject: {
						/**
						 * R​a​w​ ​S​u​b​j​e​c​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​r​a​w​ ​s​u​b​j​e​c​t​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​r​a​w​ ​s​u​b​j​e​c​t​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						longDesc: string
					}
					recipient: {
						/**
						 * R​e​c​i​p​i​e​n​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​r​e​c​i​p​i​e​n​t
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​r​e​c​i​p​i​e​n​t
						 */
						longDesc: string
					}
					requester_id: {
						/**
						 * R​e​q​u​e​s​t​e​r​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​r​e​q​u​e​s​t​e​r
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​r​e​q​u​e​s​t​e​r
						 */
						longDesc: string
					}
					sharing_agreement_ids: {
						/**
						 * S​h​a​r​i​n​g​ ​A​g​r​e​e​m​e​n​t​ ​I​D​s
						 */
						displayName: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​s​h​a​r​i​n​g​ ​a​g​r​e​e​m​e​n​t​s
						 */
						shortDesc: string
						/**
						 * I​D​s​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​s​h​a​r​i​n​g​ ​a​g​r​e​e​m​e​n​t​s
						 */
						longDesc: string
					}
					status: {
						/**
						 * S​t​a​t​u​s
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​s​t​a​t​u​s
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​s​t​a​t​u​s
						 */
						longDesc: string
					}
					submitter_id: {
						/**
						 * S​u​b​m​i​t​t​e​r​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​s​u​b​m​i​t​t​e​r
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t​’​s​ ​s​u​b​m​i​t​t​e​r
						 */
						longDesc: string
					}
					tags: {
						/**
						 * T​a​g​s
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​t​a​g​s
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​t​a​g​s
						 */
						longDesc: string
					}
					type: {
						/**
						 * T​y​p​e
						 */
						displayName: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​t​y​p​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​t​i​c​k​e​t​’​s​ ​t​y​p​e
						 */
						longDesc: string
					}
					updated_at: {
						/**
						 * U​p​d​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						longDesc: string
					}
					satisfaction_rating: {
						/**
						 * S​a​t​i​s​f​a​c​t​i​o​n​ ​R​a​t​i​n​g
						 */
						displayName: string
						/**
						 * S​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						shortDesc: string
						/**
						 * S​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
						 */
						longDesc: string
						score: {
							/**
							 * S​c​o​r​e
							 */
							displayName: string
							/**
							 * S​c​o​r​e​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							shortDesc: string
							/**
							 * S​c​o​r​e​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							longDesc: string
						}
						comment: {
							/**
							 * C​o​m​m​e​n​t
							 */
							displayName: string
							/**
							 * C​o​m​m​e​n​t​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							shortDesc: string
							/**
							 * C​o​m​m​e​n​t​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							longDesc: string
						}
						id: {
							/**
							 * I​D
							 */
							displayName: string
							/**
							 * I​D​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							shortDesc: string
							/**
							 * I​D​ ​o​f​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g
							 */
							longDesc: string
						}
						created_at: {
							/**
							 * C​r​e​a​t​e​d​ ​A​t
							 */
							displayName: string
							/**
							 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​w​a​s​ ​c​r​e​a​t​e​d
							 */
							shortDesc: string
							/**
							 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​w​a​s​ ​c​r​e​a​t​e​d
							 */
							longDesc: string
						}
						updated_at: {
							/**
							 * U​p​d​a​t​e​d​ ​A​t
							 */
							displayName: string
							/**
							 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
							 */
							shortDesc: string
							/**
							 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​s​a​t​i​s​f​a​c​t​i​o​n​ ​r​a​t​i​n​g​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
							 */
							longDesc: string
						}
					}
					via: {
						/**
						 * V​i​a
						 */
						displayName: string
						/**
						 * C​h​a​n​n​e​l​ ​t​h​r​o​u​g​h​ ​w​h​i​c​h​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						shortDesc: string
						/**
						 * C​h​a​n​n​e​l​ ​t​h​r​o​u​g​h​ ​w​h​i​c​h​ ​t​h​e​ ​t​i​c​k​e​t​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						longDesc: string
						channel: {
							/**
							 * C​h​a​n​n​e​l
							 */
							displayName: string
							/**
							 * C​h​a​n​n​e​l​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
							 */
							shortDesc: string
							/**
							 * C​h​a​n​n​e​l​ ​o​f​ ​t​h​e​ ​t​i​c​k​e​t
							 */
							longDesc: string
						}
					}
					count: {
						/**
						 * C​o​u​n​t
						 */
						displayName: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						shortDesc: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						longDesc: string
					}
					audit: {
						/**
						 * A​u​d​i​t
						 */
						displayName: string
						/**
						 * A​u​d​i​t​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						shortDesc: string
						/**
						 * A​u​d​i​t​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						longDesc: string
					}
					events: {
						/**
						 * E​v​e​n​t​s
						 */
						displayName: string
						/**
						 * E​v​e​n​t​s​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						shortDesc: string
						/**
						 * E​v​e​n​t​s​ ​o​f​ ​t​i​c​k​e​t​s
						 */
						longDesc: string
					}
				}
				groups: {
					created_at: {
						/**
						 * C​r​e​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​g​r​o​u​p​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​g​r​o​u​p​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						longDesc: string
					}
					'default': {
						/**
						 * D​e​f​a​u​l​t
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​d​e​f​a​u​l​t
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​d​e​f​a​u​l​t
						 */
						longDesc: string
					}
					description: {
						/**
						 * D​e​s​c​r​i​p​t​i​o​n
						 */
						displayName: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​d​e​s​c​r​i​p​t​i​o​n
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​d​e​s​c​r​i​p​t​i​o​n
						 */
						longDesc: string
					}
					id: {
						/**
						 * I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​I​D
						 */
						longDesc: string
					}
					name: {
						/**
						 * N​a​m​e
						 */
						displayName: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​n​a​m​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​n​a​m​e
						 */
						longDesc: string
					}
					updated_at: {
						/**
						 * U​p​d​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​g​r​o​u​p​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​g​r​o​u​p​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						longDesc: string
					}
					count: {
						/**
						 * C​o​u​n​t
						 */
						displayName: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​g​r​o​u​p​s
						 */
						shortDesc: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​g​r​o​u​p​s
						 */
						longDesc: string
					}
					deleted: {
						/**
						 * D​e​l​e​t​e​d
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​d​e​l​e​t​e​d
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​d​e​l​e​t​e​d
						 */
						longDesc: string
					}
					is_public: {
						/**
						 * I​s​ ​P​u​b​l​i​c
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​p​u​b​l​i​c
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​g​r​o​u​p​ ​i​s​ ​p​u​b​l​i​c
						 */
						longDesc: string
					}
					url: {
						/**
						 * U​R​L
						 */
						displayName: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​U​R​L
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​g​r​o​u​p​’​s​ ​U​R​L
						 */
						longDesc: string
					}
					groups: {
						/**
						 * G​r​o​u​p​s
						 */
						displayName: string
						/**
						 * G​r​o​u​p​s
						 */
						shortDesc: string
						/**
						 * G​r​o​u​p​s
						 */
						longDesc: string
					}
					users: {
						/**
						 * U​s​e​r​s
						 */
						displayName: string
						/**
						 * U​s​e​r​s
						 */
						shortDesc: string
						/**
						 * U​s​e​r​s
						 */
						longDesc: string
					}
					next_page: {
						/**
						 * N​e​x​t​ ​P​a​g​e
						 */
						displayName: string
						/**
						 * N​e​x​t​ ​p​a​g​e​ ​o​f​ ​g​r​o​u​p​s
						 */
						shortDesc: string
						/**
						 * N​e​x​t​ ​p​a​g​e​ ​o​f​ ​g​r​o​u​p​s
						 */
						longDesc: string
					}
					previoud_page: {
						/**
						 * P​r​e​v​i​o​u​s​ ​P​a​g​e
						 */
						displayName: string
						/**
						 * P​r​e​v​i​o​u​s​ ​p​a​g​e​ ​o​f​ ​g​r​o​u​p​s
						 */
						shortDesc: string
						/**
						 * P​r​e​v​i​o​u​s​ ​p​a​g​e​ ​o​f​ ​g​r​o​u​p​s
						 */
						longDesc: string
					}
				}
				organizations: {
					/**
					 * O​r​g​a​n​i​z​a​t​i​o​n​s
					 */
					displayName: string
					/**
					 * O​r​g​a​n​i​z​a​t​i​o​n​s
					 */
					shortDesc: string
					/**
					 * O​r​g​a​n​i​z​a​t​i​o​n​s
					 */
					longDesc: string
					count: {
						/**
						 * C​o​u​n​t
						 */
						displayName: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​o​r​g​a​n​i​z​a​t​i​o​n​s
						 */
						shortDesc: string
						/**
						 * C​o​u​n​t​ ​o​f​ ​o​r​g​a​n​i​z​a​t​i​o​n​s
						 */
						longDesc: string
					}
					next_page: {
						/**
						 * N​e​x​t​ ​P​a​g​e
						 */
						displayName: string
						/**
						 * N​e​x​t​ ​p​a​g​e​ ​o​f​ ​o​r​g​a​n​i​z​a​t​i​o​n​s
						 */
						shortDesc: string
						/**
						 * N​e​x​t​ ​p​a​g​e​ ​o​f​ ​o​r​g​a​n​i​z​a​t​i​o​n​s
						 */
						longDesc: string
					}
					created_at: {
						/**
						 * C​r​e​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​w​a​s​ ​c​r​e​a​t​e​d
						 */
						longDesc: string
					}
					details: {
						/**
						 * D​e​t​a​i​l​s
						 */
						displayName: string
						/**
						 * D​e​t​a​i​l​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						shortDesc: string
						/**
						 * D​e​t​a​i​l​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						longDesc: string
					}
					domain_names: {
						/**
						 * D​o​m​a​i​n​ ​N​a​m​e​s
						 */
						displayName: string
						/**
						 * D​o​m​a​i​n​ ​n​a​m​e​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						shortDesc: string
						/**
						 * D​o​m​a​i​n​ ​n​a​m​e​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						longDesc: string
					}
					external_id: {
						/**
						 * E​x​t​e​r​n​a​l​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​e​x​t​e​r​n​a​l​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​e​x​t​e​r​n​a​l​ ​I​D
						 */
						longDesc: string
					}
					group_id: {
						/**
						 * G​r​o​u​p​ ​I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​g​r​o​u​p
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​I​D​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​g​r​o​u​p
						 */
						longDesc: string
					}
					id: {
						/**
						 * I​D
						 */
						displayName: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​I​D
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​I​D
						 */
						longDesc: string
					}
					name: {
						/**
						 * N​a​m​e
						 */
						displayName: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​n​a​m​e
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​n​a​m​e
						 */
						longDesc: string
					}
					notes: {
						/**
						 * N​o​t​e​s
						 */
						displayName: string
						/**
						 * N​o​t​e​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						shortDesc: string
						/**
						 * N​o​t​e​s​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
						 */
						longDesc: string
					}
					organization_fields: {
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​F​i​e​l​d​s
						 */
						displayName: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​s
						 */
						shortDesc: string
						/**
						 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​s
						 */
						longDesc: string
						datepudding: {
							/**
							 * D​a​t​e​P​u​d​d​i​n​g
							 */
							displayName: string
							/**
							 * D​a​t​e​P​u​d​d​i​n​g​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
							 */
							shortDesc: string
							/**
							 * D​a​t​e​P​u​d​d​i​n​g​ ​o​f​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
							 */
							longDesc: string
						}
						org_field_1: {
							/**
							 * O​r​g​ ​F​i​e​l​d​ ​1
							 */
							displayName: string
							/**
							 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​ ​1
							 */
							shortDesc: string
							/**
							 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​ ​1
							 */
							longDesc: string
						}
						org_field_2: {
							/**
							 * O​r​g​ ​F​i​e​l​d​ ​2
							 */
							displayName: string
							/**
							 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​ ​2
							 */
							shortDesc: string
							/**
							 * O​r​g​a​n​i​z​a​t​i​o​n​ ​f​i​e​l​d​ ​2
							 */
							longDesc: string
						}
					}
					shared_comments: {
						/**
						 * S​h​a​r​e​d​ ​C​o​m​m​e​n​t​s
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​h​a​s​ ​s​h​a​r​e​d​ ​c​o​m​m​e​n​t​s
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​h​a​s​ ​s​h​a​r​e​d​ ​c​o​m​m​e​n​t​s
						 */
						longDesc: string
					}
					shared_tickets: {
						/**
						 * S​h​a​r​e​d​ ​T​i​c​k​e​t​s
						 */
						displayName: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​h​a​s​ ​s​h​a​r​e​d​ ​t​i​c​k​e​t​s
						 */
						shortDesc: string
						/**
						 * W​h​e​t​h​e​r​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​h​a​s​ ​s​h​a​r​e​d​ ​t​i​c​k​e​t​s
						 */
						longDesc: string
					}
					tags: {
						/**
						 * T​a​g​s
						 */
						displayName: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​t​a​g​s
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​t​a​g​s
						 */
						longDesc: string
					}
					updated_at: {
						/**
						 * U​p​d​a​t​e​d​ ​A​t
						 */
						displayName: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​d​a​t​e​ ​a​n​d​ ​t​i​m​e​ ​t​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​w​a​s​ ​l​a​s​t​ ​u​p​d​a​t​e​d
						 */
						longDesc: string
					}
					url: {
						/**
						 * U​R​L
						 */
						displayName: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​U​R​L
						 */
						shortDesc: string
						/**
						 * T​h​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​’​s​ ​U​R​L
						 */
						longDesc: string
					}
				}
			}
		}
	}
}

export type TranslationFunctions = {
	common: {
	}
	apps: {
		zendesk: {
			/**
			 * Zendesk
			 */
			displayName: () => LocalizedString
			/**
			 * Collection of actions to interact with Zendesk API
			 */
			shortDesc: () => LocalizedString
			/**
			 * Collection of actions to interact with Zendesk API
			 */
			longDesc: () => LocalizedString
			actions: {
				users: {
					get_user: {
						/**
						 * Get User
						 */
						displayName: () => LocalizedString
						/**
						 * Get user by ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * Get user by ID
						 */
						longDesc: () => LocalizedString
					}
					user_id: {
						/**
						 * User ID
						 */
						displayName: () => LocalizedString
						/**
						 * User ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * User ID
						 */
						longDesc: () => LocalizedString
					}
					items: {
						/**
						 * Items
						 */
						displayName: () => LocalizedString
						/**
						 * Items
						 */
						shortDesc: () => LocalizedString
						/**
						 * Items
						 */
						longDesc: () => LocalizedString
					}
					users: {
						/**
						 * Users
						 */
						displayName: () => LocalizedString
						/**
						 * Users
						 */
						shortDesc: () => LocalizedString
						/**
						 * Users
						 */
						longDesc: () => LocalizedString
						id: {
							/**
							 * ID
							 */
							displayName: () => LocalizedString
							/**
							 * ID
							 */
							shortDesc: () => LocalizedString
							/**
							 * ID
							 */
							longDesc: () => LocalizedString
						}
						name: {
							/**
							 * Name
							 */
							displayName: () => LocalizedString
							/**
							 * Name
							 */
							shortDesc: () => LocalizedString
							/**
							 * Name
							 */
							longDesc: () => LocalizedString
						}
					}
					active: {
						/**
						 * Active
						 */
						displayName: () => LocalizedString
						/**
						 * Active
						 */
						shortDesc: () => LocalizedString
						/**
						 * Active
						 */
						longDesc: () => LocalizedString
					}
					name: {
						/**
						 * Name
						 */
						displayName: () => LocalizedString
						/**
						 * Name
						 */
						shortDesc: () => LocalizedString
						/**
						 * Name
						 */
						longDesc: () => LocalizedString
					}
					custom_role_id: {
						/**
						 * Custom Role ID
						 */
						displayName: () => LocalizedString
						/**
						 * Custom Role ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * Custom Role ID
						 */
						longDesc: () => LocalizedString
					}
					email: {
						/**
						 * Email
						 */
						displayName: () => LocalizedString
						/**
						 * Email
						 */
						shortDesc: () => LocalizedString
						/**
						 * Email
						 */
						longDesc: () => LocalizedString
					}
					organization: {
						/**
						 * Organization
						 */
						displayName: () => LocalizedString
						/**
						 * Organization
						 */
						shortDesc: () => LocalizedString
						/**
						 * Organization
						 */
						longDesc: () => LocalizedString
					}
					role: {
						/**
						 * Role
						 */
						displayName: () => LocalizedString
						/**
						 * Role
						 */
						shortDesc: () => LocalizedString
						/**
						 * Role
						 */
						longDesc: () => LocalizedString
					}
					role_type: {
						/**
						 * Role Type
						 */
						displayName: () => LocalizedString
						/**
						 * Role Type
						 */
						shortDesc: () => LocalizedString
						/**
						 * Role Type
						 */
						longDesc: () => LocalizedString
					}
					organization_id: {
						/**
						 * Organization ID
						 */
						displayName: () => LocalizedString
						/**
						 * Organization ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * Organization ID
						 */
						longDesc: () => LocalizedString
					}
				}
				attachments: {
					content_type: {
						/**
						 * Content Type
						 */
						displayName: () => LocalizedString
						/**
						 * Content Type
						 */
						shortDesc: () => LocalizedString
						/**
						 * Content Type
						 */
						longDesc: () => LocalizedString
					}
					content_url: {
						/**
						 * Content URL
						 */
						displayName: () => LocalizedString
						/**
						 * Content URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * Content URL
						 */
						longDesc: () => LocalizedString
					}
					deleted: {
						/**
						 * Deleted
						 */
						displayName: () => LocalizedString
						/**
						 * Deleted
						 */
						shortDesc: () => LocalizedString
						/**
						 * Deleted
						 */
						longDesc: () => LocalizedString
					}
					file_name: {
						/**
						 * File Name
						 */
						displayName: () => LocalizedString
						/**
						 * File Name
						 */
						shortDesc: () => LocalizedString
						/**
						 * File Name
						 */
						longDesc: () => LocalizedString
					}
					height: {
						/**
						 * Height
						 */
						displayName: () => LocalizedString
						/**
						 * Height
						 */
						shortDesc: () => LocalizedString
						/**
						 * Height
						 */
						longDesc: () => LocalizedString
					}
					id: {
						/**
						 * ID
						 */
						displayName: () => LocalizedString
						/**
						 * ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * ID
						 */
						longDesc: () => LocalizedString
					}
					inline: {
						/**
						 * Inline
						 */
						displayName: () => LocalizedString
						/**
						 * Inline
						 */
						shortDesc: () => LocalizedString
						/**
						 * Inline
						 */
						longDesc: () => LocalizedString
					}
					size: {
						/**
						 * Size
						 */
						displayName: () => LocalizedString
						/**
						 * Size
						 */
						shortDesc: () => LocalizedString
						/**
						 * Size
						 */
						longDesc: () => LocalizedString
					}
					thumbnails: {
						/**
						 * Thumbnails
						 */
						displayName: () => LocalizedString
						/**
						 * Thumbnails
						 */
						shortDesc: () => LocalizedString
						/**
						 * Thumbnails
						 */
						longDesc: () => LocalizedString
					}
					url: {
						/**
						 * URL
						 */
						displayName: () => LocalizedString
						/**
						 * URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * URL
						 */
						longDesc: () => LocalizedString
					}
					width: {
						/**
						 * Width
						 */
						displayName: () => LocalizedString
						/**
						 * Width
						 */
						shortDesc: () => LocalizedString
						/**
						 * Width
						 */
						longDesc: () => LocalizedString
					}
					mapped_content_url: {
						/**
						 * Mapped Content URL
						 */
						displayName: () => LocalizedString
						/**
						 * Mapped Content URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * Mapped Content URL
						 */
						longDesc: () => LocalizedString
					}
					upload: {
						/**
						 * Upload
						 */
						displayName: () => LocalizedString
						/**
						 * Upload an attachment
						 */
						shortDesc: () => LocalizedString
						/**
						 * Upload an attachment
						 */
						longDesc: () => LocalizedString
					}
					token: {
						/**
						 * Zendesk Token
						 */
						displayName: () => LocalizedString
						/**
						 * Zendesk API token
						 */
						shortDesc: () => LocalizedString
						/**
						 * Zendesk API token
						 */
						longDesc: () => LocalizedString
					}
				}
				tickets: {
					comment: {
						/**
						 * Comment
						 */
						displayName: () => LocalizedString
						/**
						 * Comment on a ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Comment on a ticket
						 */
						longDesc: () => LocalizedString
					}
					subject: {
						/**
						 * Subject
						 */
						displayName: () => LocalizedString
						/**
						 * Subject of a ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Subject of a ticket
						 */
						longDesc: () => LocalizedString
					}
					priority: {
						/**
						 * Priority
						 */
						displayName: () => LocalizedString
						/**
						 * Priority of a ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Priority of a ticket
						 */
						longDesc: () => LocalizedString
					}
					create_ticket: {
						/**
						 * Create Ticket
						 */
						displayName: () => LocalizedString
						/**
						 * Create a new ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Create a new ticket
						 */
						longDesc: () => LocalizedString
					}
					update_ticket: {
						/**
						 * Update Ticket
						 */
						displayName: () => LocalizedString
						/**
						 * Update a ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Update a ticket
						 */
						longDesc: () => LocalizedString
					}
					get_ticket: {
						/**
						 * Get Ticket
						 */
						displayName: () => LocalizedString
						/**
						 * Get a ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Get a ticket
						 */
						longDesc: () => LocalizedString
					}
					ticket_id: {
						/**
						 * Ticket ID
						 */
						displayName: () => LocalizedString
						/**
						 * Ticket ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * Ticket ID
						 */
						longDesc: () => LocalizedString
					}
					created_at: {
						/**
						 * Created At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the ticket was created
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the ticket was created
						 */
						longDesc: () => LocalizedString
					}
					name: {
						/**
						 * Name
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s name
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s name
						 */
						longDesc: () => LocalizedString
					}
					collaborator_ids: {
						/**
						 * Collaborator IDs
						 */
						displayName: () => LocalizedString
						/**
						 * IDs of the ticket’s collaborators
						 */
						shortDesc: () => LocalizedString
						/**
						 * IDs of the ticket’s collaborators
						 */
						longDesc: () => LocalizedString
					}
					assignee_id: {
						/**
						 * Assignee ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s assignee
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s assignee
						 */
						longDesc: () => LocalizedString
					}
					custom_fields: {
						/**
						 * Custom Fields
						 */
						displayName: () => LocalizedString
						/**
						 * Custom fields of the ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Custom fields of the ticket
						 */
						longDesc: () => LocalizedString
					}
					custom_status_id: {
						/**
						 * Custom Status ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s custom status
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s custom status
						 */
						longDesc: () => LocalizedString
					}
					description: {
						/**
						 * Description
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s description
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s description
						 */
						longDesc: () => LocalizedString
					}
					url: {
						/**
						 * URL
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s URL
						 */
						longDesc: () => LocalizedString
					}
					due_at: {
						/**
						 * Due At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the ticket is due
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the ticket is due
						 */
						longDesc: () => LocalizedString
					}
					external_id: {
						/**
						 * External ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s external ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s external ID
						 */
						longDesc: () => LocalizedString
					}
					follower_ids: {
						/**
						 * Follower IDs
						 */
						displayName: () => LocalizedString
						/**
						 * IDs of the ticket’s followers
						 */
						shortDesc: () => LocalizedString
						/**
						 * IDs of the ticket’s followers
						 */
						longDesc: () => LocalizedString
					}
					from_messaging_channel: {
						/**
						 * From Messaging Channel
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the ticket was created from a messaging channel
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the ticket was created from a messaging channel
						 */
						longDesc: () => LocalizedString
					}
					group_id: {
						/**
						 * Group ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s group
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s group
						 */
						longDesc: () => LocalizedString
					}
					has_incidents: {
						/**
						 * Group ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s group
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s group
						 */
						longDesc: () => LocalizedString
					}
					id: {
						/**
						 * ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s ID
						 */
						longDesc: () => LocalizedString
					}
					organization_id: {
						/**
						 * Organization ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s organization
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s organization
						 */
						longDesc: () => LocalizedString
					}
					portal_id: {
						/**
						 * Portal ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s portal
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s portal
						 */
						longDesc: () => LocalizedString
					}
					problem_id: {
						/**
						 * Problem ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s problem
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s problem
						 */
						longDesc: () => LocalizedString
					}
					raw_subject: {
						/**
						 * Raw Subject
						 */
						displayName: () => LocalizedString
						/**
						 * The raw subject of the ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * The raw subject of the ticket
						 */
						longDesc: () => LocalizedString
					}
					recipient: {
						/**
						 * Recipient
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s recipient
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s recipient
						 */
						longDesc: () => LocalizedString
					}
					requester_id: {
						/**
						 * Requester ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s requester
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s requester
						 */
						longDesc: () => LocalizedString
					}
					sharing_agreement_ids: {
						/**
						 * Sharing Agreement IDs
						 */
						displayName: () => LocalizedString
						/**
						 * IDs of the ticket’s sharing agreements
						 */
						shortDesc: () => LocalizedString
						/**
						 * IDs of the ticket’s sharing agreements
						 */
						longDesc: () => LocalizedString
					}
					status: {
						/**
						 * Status
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s status
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s status
						 */
						longDesc: () => LocalizedString
					}
					submitter_id: {
						/**
						 * Submitter ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the ticket’s submitter
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the ticket’s submitter
						 */
						longDesc: () => LocalizedString
					}
					tags: {
						/**
						 * Tags
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s tags
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s tags
						 */
						longDesc: () => LocalizedString
					}
					type: {
						/**
						 * Type
						 */
						displayName: () => LocalizedString
						/**
						 * The ticket’s type
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ticket’s type
						 */
						longDesc: () => LocalizedString
					}
					updated_at: {
						/**
						 * Updated At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the ticket was last updated
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the ticket was last updated
						 */
						longDesc: () => LocalizedString
					}
					satisfaction_rating: {
						/**
						 * Satisfaction Rating
						 */
						displayName: () => LocalizedString
						/**
						 * Satisfaction rating of the ticket
						 */
						shortDesc: () => LocalizedString
						/**
						 * Satisfaction rating of the ticket
						 */
						longDesc: () => LocalizedString
						score: {
							/**
							 * Score
							 */
							displayName: () => LocalizedString
							/**
							 * Score of the satisfaction rating
							 */
							shortDesc: () => LocalizedString
							/**
							 * Score of the satisfaction rating
							 */
							longDesc: () => LocalizedString
						}
						comment: {
							/**
							 * Comment
							 */
							displayName: () => LocalizedString
							/**
							 * Comment of the satisfaction rating
							 */
							shortDesc: () => LocalizedString
							/**
							 * Comment of the satisfaction rating
							 */
							longDesc: () => LocalizedString
						}
						id: {
							/**
							 * ID
							 */
							displayName: () => LocalizedString
							/**
							 * ID of the satisfaction rating
							 */
							shortDesc: () => LocalizedString
							/**
							 * ID of the satisfaction rating
							 */
							longDesc: () => LocalizedString
						}
						created_at: {
							/**
							 * Created At
							 */
							displayName: () => LocalizedString
							/**
							 * The date and time the satisfaction rating was created
							 */
							shortDesc: () => LocalizedString
							/**
							 * The date and time the satisfaction rating was created
							 */
							longDesc: () => LocalizedString
						}
						updated_at: {
							/**
							 * Updated At
							 */
							displayName: () => LocalizedString
							/**
							 * The date and time the satisfaction rating was last updated
							 */
							shortDesc: () => LocalizedString
							/**
							 * The date and time the satisfaction rating was last updated
							 */
							longDesc: () => LocalizedString
						}
					}
					via: {
						/**
						 * Via
						 */
						displayName: () => LocalizedString
						/**
						 * Channel through which the ticket was created
						 */
						shortDesc: () => LocalizedString
						/**
						 * Channel through which the ticket was created
						 */
						longDesc: () => LocalizedString
						channel: {
							/**
							 * Channel
							 */
							displayName: () => LocalizedString
							/**
							 * Channel of the ticket
							 */
							shortDesc: () => LocalizedString
							/**
							 * Channel of the ticket
							 */
							longDesc: () => LocalizedString
						}
					}
					count: {
						/**
						 * Count
						 */
						displayName: () => LocalizedString
						/**
						 * Count of tickets
						 */
						shortDesc: () => LocalizedString
						/**
						 * Count of tickets
						 */
						longDesc: () => LocalizedString
					}
					audit: {
						/**
						 * Audit
						 */
						displayName: () => LocalizedString
						/**
						 * Audit of tickets
						 */
						shortDesc: () => LocalizedString
						/**
						 * Audit of tickets
						 */
						longDesc: () => LocalizedString
					}
					events: {
						/**
						 * Events
						 */
						displayName: () => LocalizedString
						/**
						 * Events of tickets
						 */
						shortDesc: () => LocalizedString
						/**
						 * Events of tickets
						 */
						longDesc: () => LocalizedString
					}
				}
				groups: {
					created_at: {
						/**
						 * Created At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the group was created
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the group was created
						 */
						longDesc: () => LocalizedString
					}
					'default': {
						/**
						 * Default
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the group is default
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the group is default
						 */
						longDesc: () => LocalizedString
					}
					description: {
						/**
						 * Description
						 */
						displayName: () => LocalizedString
						/**
						 * The group’s description
						 */
						shortDesc: () => LocalizedString
						/**
						 * The group’s description
						 */
						longDesc: () => LocalizedString
					}
					id: {
						/**
						 * ID
						 */
						displayName: () => LocalizedString
						/**
						 * The group’s ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * The group’s ID
						 */
						longDesc: () => LocalizedString
					}
					name: {
						/**
						 * Name
						 */
						displayName: () => LocalizedString
						/**
						 * The group’s name
						 */
						shortDesc: () => LocalizedString
						/**
						 * The group’s name
						 */
						longDesc: () => LocalizedString
					}
					updated_at: {
						/**
						 * Updated At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the group was last updated
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the group was last updated
						 */
						longDesc: () => LocalizedString
					}
					count: {
						/**
						 * Count
						 */
						displayName: () => LocalizedString
						/**
						 * Count of groups
						 */
						shortDesc: () => LocalizedString
						/**
						 * Count of groups
						 */
						longDesc: () => LocalizedString
					}
					deleted: {
						/**
						 * Deleted
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the group is deleted
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the group is deleted
						 */
						longDesc: () => LocalizedString
					}
					is_public: {
						/**
						 * Is Public
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the group is public
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the group is public
						 */
						longDesc: () => LocalizedString
					}
					url: {
						/**
						 * URL
						 */
						displayName: () => LocalizedString
						/**
						 * The group’s URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * The group’s URL
						 */
						longDesc: () => LocalizedString
					}
					groups: {
						/**
						 * Groups
						 */
						displayName: () => LocalizedString
						/**
						 * Groups
						 */
						shortDesc: () => LocalizedString
						/**
						 * Groups
						 */
						longDesc: () => LocalizedString
					}
					users: {
						/**
						 * Users
						 */
						displayName: () => LocalizedString
						/**
						 * Users
						 */
						shortDesc: () => LocalizedString
						/**
						 * Users
						 */
						longDesc: () => LocalizedString
					}
					next_page: {
						/**
						 * Next Page
						 */
						displayName: () => LocalizedString
						/**
						 * Next page of groups
						 */
						shortDesc: () => LocalizedString
						/**
						 * Next page of groups
						 */
						longDesc: () => LocalizedString
					}
					previoud_page: {
						/**
						 * Previous Page
						 */
						displayName: () => LocalizedString
						/**
						 * Previous page of groups
						 */
						shortDesc: () => LocalizedString
						/**
						 * Previous page of groups
						 */
						longDesc: () => LocalizedString
					}
				}
				organizations: {
					/**
					 * Organizations
					 */
					displayName: () => LocalizedString
					/**
					 * Organizations
					 */
					shortDesc: () => LocalizedString
					/**
					 * Organizations
					 */
					longDesc: () => LocalizedString
					count: {
						/**
						 * Count
						 */
						displayName: () => LocalizedString
						/**
						 * Count of organizations
						 */
						shortDesc: () => LocalizedString
						/**
						 * Count of organizations
						 */
						longDesc: () => LocalizedString
					}
					next_page: {
						/**
						 * Next Page
						 */
						displayName: () => LocalizedString
						/**
						 * Next page of organizations
						 */
						shortDesc: () => LocalizedString
						/**
						 * Next page of organizations
						 */
						longDesc: () => LocalizedString
					}
					created_at: {
						/**
						 * Created At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the organization was created
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the organization was created
						 */
						longDesc: () => LocalizedString
					}
					details: {
						/**
						 * Details
						 */
						displayName: () => LocalizedString
						/**
						 * Details of the organization
						 */
						shortDesc: () => LocalizedString
						/**
						 * Details of the organization
						 */
						longDesc: () => LocalizedString
					}
					domain_names: {
						/**
						 * Domain Names
						 */
						displayName: () => LocalizedString
						/**
						 * Domain names of the organization
						 */
						shortDesc: () => LocalizedString
						/**
						 * Domain names of the organization
						 */
						longDesc: () => LocalizedString
					}
					external_id: {
						/**
						 * External ID
						 */
						displayName: () => LocalizedString
						/**
						 * The organization’s external ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * The organization’s external ID
						 */
						longDesc: () => LocalizedString
					}
					group_id: {
						/**
						 * Group ID
						 */
						displayName: () => LocalizedString
						/**
						 * The ID of the organization’s group
						 */
						shortDesc: () => LocalizedString
						/**
						 * The ID of the organization’s group
						 */
						longDesc: () => LocalizedString
					}
					id: {
						/**
						 * ID
						 */
						displayName: () => LocalizedString
						/**
						 * The organization’s ID
						 */
						shortDesc: () => LocalizedString
						/**
						 * The organization’s ID
						 */
						longDesc: () => LocalizedString
					}
					name: {
						/**
						 * Name
						 */
						displayName: () => LocalizedString
						/**
						 * The organization’s name
						 */
						shortDesc: () => LocalizedString
						/**
						 * The organization’s name
						 */
						longDesc: () => LocalizedString
					}
					notes: {
						/**
						 * Notes
						 */
						displayName: () => LocalizedString
						/**
						 * Notes of the organization
						 */
						shortDesc: () => LocalizedString
						/**
						 * Notes of the organization
						 */
						longDesc: () => LocalizedString
					}
					organization_fields: {
						/**
						 * Organization Fields
						 */
						displayName: () => LocalizedString
						/**
						 * Organization fields
						 */
						shortDesc: () => LocalizedString
						/**
						 * Organization fields
						 */
						longDesc: () => LocalizedString
						datepudding: {
							/**
							 * DatePudding
							 */
							displayName: () => LocalizedString
							/**
							 * DatePudding of the organization
							 */
							shortDesc: () => LocalizedString
							/**
							 * DatePudding of the organization
							 */
							longDesc: () => LocalizedString
						}
						org_field_1: {
							/**
							 * Org Field 1
							 */
							displayName: () => LocalizedString
							/**
							 * Organization field 1
							 */
							shortDesc: () => LocalizedString
							/**
							 * Organization field 1
							 */
							longDesc: () => LocalizedString
						}
						org_field_2: {
							/**
							 * Org Field 2
							 */
							displayName: () => LocalizedString
							/**
							 * Organization field 2
							 */
							shortDesc: () => LocalizedString
							/**
							 * Organization field 2
							 */
							longDesc: () => LocalizedString
						}
					}
					shared_comments: {
						/**
						 * Shared Comments
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the organization has shared comments
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the organization has shared comments
						 */
						longDesc: () => LocalizedString
					}
					shared_tickets: {
						/**
						 * Shared Tickets
						 */
						displayName: () => LocalizedString
						/**
						 * Whether the organization has shared tickets
						 */
						shortDesc: () => LocalizedString
						/**
						 * Whether the organization has shared tickets
						 */
						longDesc: () => LocalizedString
					}
					tags: {
						/**
						 * Tags
						 */
						displayName: () => LocalizedString
						/**
						 * The organization’s tags
						 */
						shortDesc: () => LocalizedString
						/**
						 * The organization’s tags
						 */
						longDesc: () => LocalizedString
					}
					updated_at: {
						/**
						 * Updated At
						 */
						displayName: () => LocalizedString
						/**
						 * The date and time the organization was last updated
						 */
						shortDesc: () => LocalizedString
						/**
						 * The date and time the organization was last updated
						 */
						longDesc: () => LocalizedString
					}
					url: {
						/**
						 * URL
						 */
						displayName: () => LocalizedString
						/**
						 * The organization’s URL
						 */
						shortDesc: () => LocalizedString
						/**
						 * The organization’s URL
						 */
						longDesc: () => LocalizedString
					}
				}
			}
		}
	}
}

export type Formatters = {}
