// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
	}
	apps: {
		zendesk: {
			/**
			 * Z​e​n​d​e​s​k
			 */
			displayName: string
			/**
			 * C​o​l​l​e​c​t​i​o​n​ ​o​f​ ​a​c​t​i​o​n​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​Z​e​n​d​e​s​k​ ​A​P​I
			 */
			shortDesc: string
			/**
			 * C​o​l​l​e​c​t​i​o​n​ ​o​f​ ​a​c​t​i​o​n​s​ ​t​o​ ​i​n​t​e​r​a​c​t​ ​w​i​t​h​ ​Z​e​n​d​e​s​k​ ​A​P​I
			 */
			longDesc: string
			actions: {
				get_user: {
					/**
					 * G​e​t​ ​U​s​e​r
					 */
					displayName: string
					/**
					 * G​e​t​ ​u​s​e​r​ ​b​y​ ​I​D
					 */
					shortDesc: string
					/**
					 * G​e​t​ ​u​s​e​r​ ​b​y​ ​I​D
					 */
					longDesc: string
				}
			}
		}
	}
}

export type TranslationFunctions = {
	common: {
	}
	apps: {
		zendesk: {
			/**
			 * Zendesk
			 */
			displayName: () => LocalizedString
			/**
			 * Collection of actions to interact with Zendesk API
			 */
			shortDesc: () => LocalizedString
			/**
			 * Collection of actions to interact with Zendesk API
			 */
			longDesc: () => LocalizedString
			actions: {
				get_user: {
					/**
					 * Get User
					 */
					displayName: () => LocalizedString
					/**
					 * Get user by ID
					 */
					shortDesc: () => LocalizedString
					/**
					 * Get user by ID
					 */
					longDesc: () => LocalizedString
				}
			}
		}
	}
}

export type Formatters = {}
