name: Pull Request Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  pull_request:
    branches:
      - dev
env:
  ZENDESK_TEST_DOMAIN: ${{ secrets.ZENDESK_TEST_DOMAIN }}
  ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
  ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
  ZENDESK_CLIENT_SECRET: ${{ secrets.ZENDESK_CLIENT_SECRET }}
  SLACK_ACCESS_TOKEN: ${{ secrets.SLACK_ACCESS_TOKEN }}
  SLACK_USER_ACCESS_TOKEN: ${{ secrets.SLACK_USER_ACCESS_TOKEN }}
  SLACK_USER_EMAIL: ${{ secrets.SLACK_USER_EMAIL }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  PullRequestTests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      QORUS_TOKEN: ${{ secrets.QORUS_TOKEN }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Get current time for the commit
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current_time
        with:
          format: YYYYMMDD-HH
          utcOffset: '+01:00'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Print head git commit message
        id: get_head_commit_message
        run: echo "::set-output name=HEAD_COMMIT_MESSAGE::$(git show -s --format=%s)"

      - uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Save release version to outputs
        id: save_release_version
        run: echo ::set-output name=version::$(node -pe "require('./package.json').version")

      - name: Installing modules
        id: install_modules
        run: |
          yarn install

      - name: Run build test
        run: |
          yarn build:test

      - name: Run unit tests
        run: |
          yarn test:ci

      # - name: Serve Storybook and run tests
      #   run: |
      #     npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
      #       "npx http-server storybook-static --port 6008 --silent" \
      #       "npx wait-on tcp:6008 && yarn test-storybook"

      # - name: Bump version with timestamp and canary tag
      #   id: bump
      #   run: |
      #     TIMESTAMP=$(date +"%Y%m%d%H%M%S")
      #     NEW_VERSION=$(npm version prerelease --preid=canary.$TIMESTAMP --no-git-tag-version)
      #     echo "New version: $NEW_VERSION"
      #     echo "::set-output name=version::$NEW_VERSION"

      # - name: Publish canary version to NPM
      #   id: npm_publish
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: canary
      #     access: public

      # - name: Create comment with canary version
      #   uses: mshick/add-pr-comment@v2
      #   with:
      #     message: |
      #       Canary version for this PR published: ${{ steps.bump.outputs.version }}
      #       ```sh
      #       yarn add @qoretechnologies/qorus-actions-catalogue@${{ steps.bump.outputs.version }}
      #       ```

      # - name: Publish to Chromatic
      #   id: chromatic_publish
      #   uses: chromaui/action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      #     exitZeroOnChanges: true
      #     allowConsoleErrors: true
      #     debug: true

      # Notify Discord if Success
      - name: Discord notification success
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          DISCORD_EMBEDS: '[{ "author": {  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "name": "${{ github.actor }}", "url": "https://github.com/${{github.actor}}" },"url": "https://github.com/${{github.repository}}/commit/${{github.sha}}","fields": [{ "name": "Commit Message", "value": "${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}"},{ "name": "Repository", "value": "[${{github.event.repository.name}}](${{github.event.repository.clone_url}})", "inline": true },{ "name": "Branch", "value": "[${{github.ref_name}}](https://github.com/${{github.repository}}/pull/${{github.ref_name}})", "inline": true },{ "name": "Event", "value": "${{github.event_name}}", "inline": true },{ "name": "Author", "value": "[${{github.actor}}](https://github.com/${{github.actor}})", "inline": true },{ "name": "Job", "value": "${{github.job}}", "inline": true},{ "name": "Version", "value": "v${{ steps.save_release_version.outputs.version }}", "inline": true},{ "name": "", "value": "🤖 [Github Action](https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id}})"}],"color":65280,"footer":{"text": "Published at ${{steps.current_time.outputs.readableTime}}"}}]'
          DISCORD_AVATAR: 'https://github.com/qoretechnologies/qorus-vscode/blob/95ad81fa8654fe83bb41f68f4de42ae088298e59/public/q-symbol-small.png?raw=true'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ':white_check_mark: Tests run #${{ github.run_number }} for [PR](${{ github.event.pull_request.html_url }}) triggered by ${{ github.triggering_actor }} *succeeded*, install the canary version via `yarn add @qoretechnologies/qorus-actions-catalogue@${{ steps.bump.outputs.version }}`.'
        if: success()

      # Notify discord if failure
      - name: Discord notification failure
        env:
          DISCORD_WEBHOOK: ${{secrets.DISCORD_WEBHOOK}}
          DISCORD_EMBEDS: '[{ "author": {  "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}", "name": "${{ github.actor }}", "url": "https://github.com/${{github.actor}}" },"url": "https://github.com/${{github.repository}}/commit/${{github.sha}}","fields": [{ "name": "Commit Message", "value": "${{ steps.get_head_commit_message.outputs.HEAD_COMMIT_MESSAGE }}"},{ "name": "Repository", "value": "[${{github.event.repository.name}}](${{github.event.repository.clone_url}})", "inline": true },{ "name": "Branch", "value": "[${{github.ref_name}}](https://github.com/${{github.repository}}/pull/${{github.ref_name}})", "inline": true },{ "name": "Event", "value": "${{github.event_name}}", "inline": true },{ "name": "Author", "value": "[${{github.actor}}](https://github.com/${{github.actor}})", "inline": true },{ "name": "Job", "value": "${{github.job}}", "inline": true },{ "name": "Version", "value": "v${{ steps.save_release_version.outputs.version }}", "inline": true},{ "name": "", "value": "🤖 [Github Action](https://github.com/${{ github.repository}}/actions/runs/${{ github.run_id}})"}],"color":16711680,"footer":{"text": "Published at ${{steps.current_time.outputs.readableTime}}"}}]'
          DISCORD_AVATAR: 'https://github.com/qoretechnologies/qorus-vscode/blob/95ad81fa8654fe83bb41f68f4de42ae088298e59/public/q-symbol-small.png?raw=true'
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: ':exclamation: Tests run #${{ github.run_number }} for [PR](${{ github.event.pull_request.html_url }}) triggered by ${{ github.triggering_actor }} *failed*!'
        if: failure()
